import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const users = [
  { name: 'Joel', user: 'joelwaiman' },
  { name: 'Fran', user: 'FranciscoDiazPaccot73' },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Adviency Challenge
        </h2>
        <a className='mt-8' href='https://twitter.com/goncy/status/1597581740746637314' target="_blank">
          <svg viewBox="0 0 512 512" height={50} width={50} fill="#00ACEE">
            <path
              d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"
            />
          </svg>
        </a>

        <ul className='flex flex-wrap gap-7 justify-center mt-24'>
          {users.map(({ name, user}) => (
            <li className='inline-flex flex-shrink-0'>
              <a
                className='text-white visited:text-neutral-400 hover:underline text-center flex flex-col gap-y-2 items-center justify-center w-20'
                href={`/${name.toLowerCase()}`}
              >
                <img
                  loading='lazy'
                  width='80px'
                  height='80px'
                  className='rounded-full w-full h-auto'
                  src={'https://unavatar.io/github/' + user}
                  alt={name}
                />
                <span className='block w-20 whitespace-nowrap overflow-hidden text-ellipsis text-xs'>
                  {name}
                </span>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
